name: E2E
on:
  push:
jobs:
  set-wp-versions:
    runs-on: ubuntu-latest
    outputs:
      wp-versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - id: set-versions
        run: |
          if [ "$GITHUB_EVENT_NAME" = "push" ];then
            echo "::set-output name=versions::[\"5.7\",\"4.9\"]"
          fi
  plugin:
    needs: set-wp-versions
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        wp_version: ${{fromJson(needs.set-wp-versions.outputs.wp-versions)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Docker Host IP
        uses: addnab/docker-run-action@v1
        with:
          image: alpine:latest
          run: apk update > /dev/null && apk add iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
